repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.0
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --report-path=out.json
        language: system
        types: [text]
        stages: [pre-commit]
